import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Plus, Trash2, Pencil, Printer, Download, Sparkles, Music2, Users, CalendarDays, GripVertical, ChevronRight, ChevronLeft, X, CheckCircle2, LogIn, UserCircle} from 'lucide-react';
import './styles.css';

const themes={0:['Sunday','saffron'],1:['Monday','slate'],2:['Tuesday','red'],3:['Wednesday','green'],4:['Thursday','gold'],5:['Friday','rose'],6:['Saturday','night']};
const categories=['Ganesha','Guru & Baba','Hanuman','Devi','Shiva','Krishna / Rama','Narayana','Sarva Dharma','Subrahmanya','Closing / Mangalam','Other'];
const starter=[{title:'Ganesha Sharanam Parama Pavanam',category:'Ganesha',pitch:'',singer:''},{title:'Sai Ram Sai Shyam Sai Bhagavan',category:'Guru & Baba',pitch:'',singer:''}];
function App(){
 const [lang,setLang]=useState('EN'); const [day,setDay]=useState(new Date().getDay()); const [tab,setTab]=useState('studio'); const [slide,setSlide]=useState(0); const [loggedIn,setLoggedIn]=useState(()=>localStorage.getItem('sai-login')||''); const [loginOpen,setLoginOpen]=useState(false); const [loginName,setLoginName]=useState('');
 const [event,setEvent]=useState({title:'Sri Sathya Sai Bhajan List',samithi:'',venue:''});
 const [singers,setSingers]=useState([]); const [bhajans,setBhajans]=useState([]); const [count,setCount]=useState(''); const [target,setTarget]=useState(null); const [form,setForm]=useState({title:'',category:'Ganesha',pitch:'',singer:'',position:''});
 const [dragIndex,setDragIndex]=useState(null); const [events,setEvents]=useState(()=>JSON.parse(localStorage.getItem('sai-events')||'[]')); const [savedId,setSavedId]=useState('');
 const theme=themes[day]; const gallery=['/images/baba-1.png','/images/baba-2.png','/images/baba-3.png','/images/baba-4.png']; const quotes=['Love all, serve all.','Help ever, hurt never.','The end of education is character.','Be good, do good, see good, speak good.'];
 useEffect(()=>{document.documentElement.dataset.theme=theme[1]},[theme]);
 useEffect(()=>{const raw=localStorage.getItem('sai-current');if(raw){const x=JSON.parse(raw);setEvent(x.event||event);setSingers(x.singers||[]);setBhajans(x.bhajans||[]) }},[]);
 useEffect(()=>localStorage.setItem('sai-current',JSON.stringify({event,singers,bhajans})),[event,singers,bhajans]);
 const labels=lang==='EN'?{studio:'Bhajan Studio',roster:'Singer roster',sequence:'Bhajan sequence',create:'Create bhajan',planner:'Sequence planner',save:'Save event',print:'Print / PDF',download:'Export list',empty:'Your bhajan flow starts here.',add:'Add bhajan',update:'Update bhajan'}:{studio:'பஜன் ஸ்டுடியோ',roster:'பாடகர்கள் பட்டியல்',sequence:'பஜன் வரிசை',create:'பஜன் உருவாக்கு',planner:'வரிசை திட்டமிடல்',save:'நிகழ்வை சேமி',print:'அச்சிடு / PDF',download:'பட்டியல் பதிவிறக்கம்',empty:'உங்கள் பஜன் வரிசை இங்கே தொடங்குகிறது.',add:'பஜன் சேர்',update:'பஜன் மாற்று'};
 function resetForm(){setForm({title:'',category:'Ganesha',pitch:'',singer:'',position:''});setTarget(null)}
 function submit(e){e.preventDefault();if(!loggedIn){alert('Please login as a devotee before adding or updating a bhajan.');setLoginOpen(true);return;}if(!form.title.trim())return;const item={...form,title:form.title.trim(),createdBy:target!==null?(bhajans[target]?.createdBy||loggedIn):loggedIn};if(target!==null){setBhajans(x=>x.map((b,i)=>i===target?item:b))}else{let next=[...bhajans];const pos=Number(form.position);if(pos>0&&pos<=next.length+1)next.splice(pos-1,0,item);else next.push(item);setBhajans(next)}alert(target!==null?'Bhajan updated successfully.':'Bhajan added successfully.');resetForm()}
 function chooseCount(v){setCount(v);if(v){setBhajans(x=>x.slice(0,Number(v)));}}
 function moveToPosition(from,to){const dest=Math.max(1,Math.min(Number(to)||1,bhajans.length));setBhajans(prev=>{const next=[...prev];const [item]=next.splice(from,1);next.splice(dest-1,0,item);return next;});}
 function edit(i){setTarget(i);setForm({...bhajans[i],position:String(i+1)});setTab('studio');window.scrollTo({top:0,behavior:'smooth'})}
 function remove(i){setBhajans(x=>x.filter((_,n)=>n!==i))}
 function saveEvent(){const id=savedId||Date.now().toString();const next={id,event,singers,bhajans};setEvents(x=>[...x.filter(a=>a.id!==id),next]);setSavedId(id);alert('Event saved locally.');}
 function loadEvent(id){const x=events.find(a=>a.id===id);if(x){setSavedId(id);setEvent(x.event);setSingers(x.singers);setBhajans(x.bhajans)}}
 function doLogin(e){e.preventDefault();if(loginName.trim()){setLoggedIn(loginName.trim());localStorage.setItem('sai-login',loginName.trim());setLoginOpen(false);}} function logout(){setLoggedIn('');localStorage.removeItem('sai-login')}
 function exportTable(){const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const rows=bhajans.map((b,i)=>`<tr><td>${i+1}</td><td>${esc(b.title)}</td><td>${esc(b.category)}</td><td>${esc(b.singer||'-')}</td><td>${esc(b.pitch||'-')}</td><td>${esc(b.createdBy||'-')}</td></tr>`).join('');const html=`<html><meta charset="UTF-8"><table border="1"><tr><th>No.</th><th>Bhajan</th><th>Category</th><th>Lead Singer</th><th>Pitch</th><th>Created By</th></tr>${rows}</table></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel'}));a.download='sai-bhajan-table.xls';a.click();URL.revokeObjectURL(a.href)}
 function exportList(){const text=[event.title,event.samithi,event.venue,'',...bhajans.map((b,i)=>`${i+1}. ${b.title} | ${b.category} | Singer: ${b.singer||'-'} | Pitch: ${b.pitch||'-'} | Created by: ${b.createdBy||'-'}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='sai-bhajan-list.txt';a.click();URL.revokeObjectURL(a.href)}
 return <div className="app">
  <header className="hero"><div className="hero-image"><img src={gallery[slide]} alt="Sri Sathya Sai Baba"/><button className="slide-prev" onClick={()=>setSlide((slide+gallery.length-1)%gallery.length)}><ChevronLeft size={15}/></button><button className="slide-next" onClick={()=>setSlide((slide+1)%gallery.length)}><ChevronRight size={15}/></button><div className="slide-dots">{gallery.map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={`Slide ${i+1}`}/>)}</div></div><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> SRI SATHYA SAI • DEVOTIONAL PLANNER</div><h1>{labels.studio}</h1><p>Design a beautiful, perfectly ordered bhajan session with singers, positions and print-ready lists.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab('studio')}><Music2 size={16}/> {labels.create}</button><button className="ghost" onClick={()=>setLang(lang==='EN'?'TA':'EN')}>{lang==='EN'?'தமிழ்':'English'}</button></div></div><div className="hero-side"><span className="day-dot"></span><b>{theme[0]}</b><small>Day colour theme</small><button className="login-button" onClick={()=>loggedIn?logout():setLoginOpen(true)}><UserCircle size={15}/> {loggedIn?`Logout ${loggedIn}`:'Login'}</button></div></header><div className="quote-strip"><span>“{quotes[slide]}”</span><small>— Sri Sathya Sai Baba</small></div>
  <nav className="tabs"><button className={tab==='studio'?'active':''} onClick={()=>setTab('studio')}>Studio</button><button className={tab==='planner'?'active':''} onClick={()=>setTab('planner')}>Planner <span>{bhajans.length}</span></button><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>Saved events</button></nav>
  {tab==='studio'&&<main className="grid-layout"><section className="main-column">
   <div className="section-heading"><div><span className="kicker">01 / {labels.roster}</span><h2><Users size={20}/> {labels.roster}</h2></div><span className="count-pill">{singers.length} singers</span></div>
   <div className="panel roster"><div className="add-row"><input placeholder="Brother Sai / Sister Geetha" value={form._singer||''} onChange={e=>setForm({...form,_singer:e.target.value})}/><button className="primary" onClick={()=>{if(form._singer?.trim()){setSingers(x=>[...new Set([...x,form._singer.trim()])]);setForm({...form,_singer:''})}}}><Plus size={16}/> Add singer</button></div><div className="chips">{singers.map((s,i)=><span className="chip" key={s}>{s}<button onClick={()=>setSingers(x=>x.filter((_,n)=>n!==i))}><X size={12}/></button></span>)}{!singers.length&&<small className="muted">Add singers first, then assign them to each bhajan.</small>}</div></div>
   <div className="section-heading"><div><span className="kicker">02 / {labels.create}</span><h2><Music2 size={20}/> {labels.create}</h2></div><span className="count-pill">{target!==null?'Editing':'New entry'}</span></div>
   <form className="panel form" onSubmit={submit}><label>Bhajan title / lyrics line<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Ganesha Sharanam Parama Pavanam"/></label><div className="two"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Pitch / key <input value={form.pitch} onChange={e=>setForm({...form,pitch:e.target.value})} placeholder="5 kattai / G#"/></label></div><div className="two"><label>Lead singer<select value={form.singer} onChange={e=>setForm({...form,singer:e.target.value})}><option value="">Not assigned</option>{singers.map(s=><option key={s}>{s}</option>)}</select></label><label>Position <input type="number" min="1" max={bhajans.length+1} value={form.position} onChange={e=>setForm({...form,position:e.target.value})} placeholder={`1–${bhajans.length+1}`}/></label></div><small className="hint">Position is optional. Enter a number to insert this bhajan exactly where you want it.</small><div className="form-actions"><button type="button" className="ghost" onClick={resetForm}>Clear</button><button className="primary" type="submit"><CheckCircle2 size={16}/>{target!==null?labels.update:labels.add}</button></div></form>
  </section><aside className="side-column"><div className="portrait-card"><img src="/images/baba-3.png"/><div><span className="kicker">A calm beginning</span><h3>Let every song become an offering.</h3><p>Arrange your session with clarity, devotion and a gentle flow.</p></div></div><div className="panel mini"><div className="mini-title"><CalendarDays size={17}/> Event details</div><input value={event.title} onChange={e=>setEvent({...event,title:e.target.value})} placeholder="Occasion name"/><input value={event.samithi} onChange={e=>setEvent({...event,samithi:e.target.value})} placeholder="Samithi / organisation"/><input value={event.venue} onChange={e=>setEvent({...event,venue:e.target.value})} placeholder="Venue / date"/><button className="primary full" onClick={saveEvent}>{labels.save}<ChevronRight size={16}/></button></div><div className="panel mini"><div className="mini-title"><Sparkles size={17}/> Optional bhajan count</div><p className="muted">Choose how many songs you want in the session. You can still add or reorder them below.</p><input className="count-input" type="number" min="1" max="100" value={count} onChange={e=>chooseCount(e.target.value)} placeholder="Enter number of bhajans"/></div></aside></main>}
  {tab==='planner'&&<main className="planner"><div className="planner-head"><div><span className="kicker">03 / {labels.planner}</span><h2>{event.title}</h2><p>{event.samithi} {event.venue&&'• '+event.venue}</p></div><div className="hero-actions"><button className="ghost" onClick={exportTable}><Download size={16}/>Excel table</button><button className="ghost" onClick={exportList}><Download size={16}/>List format</button><button className="primary" onClick={()=>window.print()}><Printer size={16}/>{labels.print}</button></div></div>{bhajans.length===0?<div className="empty"><Music2 size={32}/><h3>{labels.empty}</h3><button className="primary" onClick={()=>setTab('studio')}>Create first bhajan</button></div>:<div className="sequence">{bhajans.map((b,i)=><article className="bhajan" draggable onDragStart={()=>setDragIndex(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragIndex!==null){moveToPosition(dragIndex,i+1);setDragIndex(null)}}} key={i}><div className="number"><GripVertical size={16}/>{String(i+1).padStart(2,'0')}</div><div className="bhajan-content"><div className="bhajan-top"><h3>{b.title}</h3><span>{b.category}</span></div><div className="meta">{b.singer&&<span>🎙 {b.singer}</span>}{b.pitch&&<span>♫ {b.pitch}</span>}<span>👤 {b.createdBy||'Unknown devotee'}</span></div></div><div className="bhajan-actions"><button onClick={()=>edit(i)}><Pencil size={16}/></button><button onClick={()=>remove(i)}><Trash2 size={16}/></button></div></article>)}</div>}</main>}
  {tab==='events'&&<main className="planner"><div className="planner-head"><div><span className="kicker">Your library</span><h2>Saved events</h2></div></div>{events.length===0?<div className="empty">No saved events yet.</div>:<div className="saved-grid">{events.map(x=><button className="saved-card" key={x.id} onClick={()=>{loadEvent(x.id);setTab('planner')}}><span>{x.event.title}</span><small>{x.bhajans.length} bhajans • {x.singers.length} singers</small><ChevronRight/></button>)}</div>}</main>}
  {loginOpen&&<div className="login-modal"><form className="login-box" onSubmit={doLogin}><button type="button" className="close-login" onClick={()=>setLoginOpen(false)}><X/></button><h2><LogIn size={20}/> Devotee login</h2><p>Enter your name to personalize this session.</p><input required value={loginName} onChange={e=>setLoginName(e.target.value)} placeholder="Your name"/><button className="primary full">Continue</button></form></div>}<footer><img src="/images/baba-2.png"/> <span>With love and devotion • Sri Sathya Sai Bhajan Studio</span></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
